/* Original compositions. No external assets or dependencies. */
const CATEGORIES = [
 ['gradients','Gradients','Градиенты','Soft fields, bold blends and impossible light.','Мягкие переливы, смелые сочетания и необычный свет.','#c6f66b','◒'],
 ['geometry','Geometry','Геометрия','Order, rhythm and shapes with a point of view.','Порядок, ритм и формы с характером.','#a49aff','◇'],
 ['particles','Particles','Частицы','Small things. Endless movement.','Маленькие элементы. Бесконечное движение.','#67d7ff','⁙'],
 ['space','Space','Космос','A little further than the ordinary.','Чуть дальше привычного мира.','#b798ff','✧'],
 ['nature','Nature','Природа','Organic motion, borrowed from the outside.','Живые формы и движение, вдохновлённые природой.','#72dfaa','❋'],
 ['abstract','Abstract','Абстракция','Happy accidents, carefully composed.','Неожиданные формы в продуманных композициях.','#ff91bd','◈'],
 ['retro','Retro & neon','Ретро и неон','Yesterday’s future, turned all the way up.','Будущее из прошлого — на полной яркости.','#ff7bce','ϟ'],
 ['minimal','Minimal & texture','Минимализм и текстуры','Quiet details. A different kind of statement.','Тихие детали, которые говорят сами за себя.','#e0cca7','▧']
].map((a,i)=>({id:a[0],en:a[1],ru:a[2],description:{en:a[3],ru:a[4]},color:a[5],symbol:a[6],index:i}));
const NAMES = [
 [
 ['Acid bloom','Лаймовое свечение','An off-centre pool of lime light.','Смещённое пятно лаймового света.'],
 ['Candy mesh','Конфетная сетка','Three soft pools overlap in a pastel mesh.','Три мягких пятна образуют пастельную сетку.'],
 ['Solar wash','Солнечный прилив','A hot diagonal stripe melts into violet.','Горячая диагональ растворяется в фиолетовом.'],
 ['Iridescent fold','Перламутровая складка','A conic spectrum folds around a bright hinge.','Конический спектр складывается вокруг светлой оси.'],
 ['Blue hour','Синий час','A low horizon glows through deep blue.','Низкий горизонт светится сквозь глубокую синеву.'],
 ['Spotlight','Прожектор','A sharp cone cuts through a dark stage.','Чёткий луч прорезает тёмную сцену.'],
 ['Peach halo','Персиковый ореол','A warm ring hangs in a pale field.','Тёплое кольцо парит в светлом поле.'],
 ['Chromatic steps','Хроматические ступени','Hard bands interrupt a smooth spectrum.','Чёткие полосы прерывают плавный спектр.'],
 ['Crosslight','Перекрёстный свет','Two luminous beams meet at right angles.','Два светящихся луча пересекаются под прямым углом.'],
 ['Midnight vignette','Полночная виньетка','An elliptical centre fades into ink.','Эллиптический центр исчезает в чернильной темноте.'],
 ['Liquid aurora','Жидкое сияние','Translucent ribbons flow in layered waves.','Полупрозрачные ленты текут слоями волн.'],
 ['Orbital blend','Орбитальный перелив','Three luminous orbs drift around a shared centre.','Три светящихся шара вращаются вокруг общего центра.'],
 ['Prism scan','Призменный скан','Vertical colour bars breathe across the canvas.','Вертикальные цветовые полосы пульсируют на холсте.'],
 ['Silk dunes','Шёлковые дюны','Smooth filled curves roll over a glowing sky.','Плавные изгибы катятся под светящимся небом.'],
 ['Colour tide','Цветовой прилив','A moving radial front spreads across the surface.','Радиальный фронт цвета движется по поверхности.'],
 ['Luminous tunnel','Световой тоннель','Nested gradients pull the eye into depth.','Вложенные градиенты уводят взгляд в глубину.'],
 ['Polar curtain','Полярный занавес','Thin spectral strands ripple vertically.','Тонкие спектральные нити колышутся по вертикали.'],
 ['Molten eclipse','Расплавленное затмение','An opaque disc crosses a luminous halo.','Непрозрачный диск пересекает светящийся ореол.'],
 ['Spectrum fan','Спектральный веер','Transparent wedges sweep around a pivot.','Прозрачные секторы движутся вокруг одной точки.'],
 ['Thermal map','Тепловая карта','A grid of glowing cells responds to travelling waves.','Сетка светящихся ячеек подчиняется бегущим волнам.']
 ],
 [
 ['Offset tiles','Смещённая плитка','Two staggered layers form a tiled rhythm.','Два смещённых слоя создают ритм плитки.'],['Bauhaus corner','Угол Баухауса','Quarter circles meet a strict split plane.','Четверти кругов пересекают строго разделённую плоскость.'],['Isometric blocks','Изометрические блоки','Three angled faces build an optical cube grid.','Три наклонные грани строят сетку оптических кубов.'],['Target practice','Мишень','Concentric rings radiate from an offset centre.','Концентрические кольца расходятся из смещённого центра.'],['Diagonal weave','Диагональное плетение','Crossed bands weave a two-axis lattice.','Пересечённые полосы сплетаются в решётку.'],['Harlequin','Арлекин','Alternating diamonds repeat across the plane.','Чередующиеся ромбы заполняют плоскость.'],['Graph paper','Миллиметровка','Fine and major grid lines establish a precise scale.','Тонкие и основные линии задают точный масштаб.'],['Half moons','Полумесяцы','Repeated semicircles form a scalloped surface.','Повторяющиеся полукруги образуют волнистую поверхность.'],['Pinwheel','Вертушка','Four conic quadrants create a graphic pinwheel.','Четыре конических сектора создают графическую вертушку.'],['Broken stripes','Ломаные полосы','A herringbone path cuts through parallel stripes.','Узор ёлочкой пересекает параллельные полосы.'],
 ['Polygon orbit','Орбиты многоугольников','Wire polygons rotate at independent rates.','Контурные многоугольники вращаются с разной скоростью.'],['Breathing grid','Дышащая сетка','A matrix of squares expands in a travelling pulse.','Матрица квадратов расширяется бегущим импульсом.'],['Triangle field','Поле треугольников','Alternating triangular tiles change their proportions.','Чередующиеся треугольные плитки меняют пропорции.'],['Spirograph','Спирограф','A rolling mathematical curve draws a complex flower.','Математическая кривая рисует сложный цветок.'],['Rotating portals','Вращающиеся порталы','Nested rectangles twist toward a vanishing point.','Вложенные прямоугольники закручиваются к точке схода.'],['Hex constellation','Шестиугольное созвездие','Hexagons breathe across a staggered lattice.','Шестиугольники пульсируют на смещённой решётке.'],['Perspective floor','Перспективная плоскость','A moving grid converges at a high horizon.','Подвижная сетка сходится у высокого горизонта.'],['Arc machine','Машина дуг','Independent circular segments turn on a shared axis.','Отдельные сегменты окружностей вращаются на общей оси.'],['Pendulum wall','Стена маятников','Suspended bobs follow progressively different periods.','Подвешенные маятники качаются с разными периодами.'],['Faceted cells','Гранёные ячейки','Faceted cells pulse around an irregular seed lattice.','Гранёные ячейки пульсируют на нерегулярной сетке.']
 ],
 [
 ['Dot matrix','Матрица точек','Even points form a precise dot matrix.','Ровные точки образуют строгую матрицу.'],['Halftone fade','Полутоновый растр','Dots dissolve through a diagonal mask.','Точки растворяются через диагональную маску.'],['Confetti paper','Конфетти','Offset rectangular flecks form a playful pattern.','Смещённые прямоугольные штрихи создают игривый узор.'],['Bubble wrap','Пузырчатая плёнка','Transparent rings repeat on a soft surface.','Прозрачные кольца повторяются на мягкой поверхности.'],['Micro stars','Микрозвёзды','Cross-shaped sparks repeat in a night field.','Крестообразные искры повторяются на ночном поле.'],['Sparse dust','Редкая пыль','Two dot scales intersect at irregular intervals.','Точки двух размеров пересекаются через неравные интервалы.'],['Perforated metal','Перфорация','Dark holes cast tiny highlights on a metallic surface.','Тёмные отверстия отбрасывают блики на металлической поверхности.'],['Rain marks','Следы дождя','Fine diagonal dashes suggest falling rain.','Тонкие диагональные штрихи напоминают дождь.'],['Pearl lattice','Жемчужная решётка','Small shaded spheres sit on a regular lattice.','Маленькие объёмные сферы расположены на ровной сетке.'],['Pixel scatter','Пиксельная россыпь','Layered square grids make a digital grain.','Слои квадратных сеток создают цифровое зерно.'],
 ['Connected minds','Созвездие связей','Nearby drifting points connect with fine lines.','Близкие движущиеся точки соединяются тонкими линиями.'],['Fireflies','Светлячки','Slow golden lights blink on drifting paths.','Медленные огоньки мигают на плавных траекториях.'],['Gravity well','Гравитационный колодец','Particles spiral toward a shared centre.','Частицы закручиваются к общему центру.'],['Snow globe','Снежный шар','Layered snowflakes drift down with a soft crosswind.','Слои снежинок опускаются под лёгким боковым ветром.'],['Bubble stream','Поток пузырей','Outlined bubbles rise with sinusoidal drift.','Контурные пузыри поднимаются по волнистой траектории.'],['Meteor shower','Метеорный дождь','Long bright tails streak diagonally across the frame.','Длинные светлые хвосты пересекают кадр по диагонали.'],['Fountain','Фонтан','A parabolic spray launches from the lower centre.','Параболические струи взлетают из нижнего центра.'],['Wave swarm','Волновой рой','Rows of particles follow a three-dimensional wave.','Ряды частиц следуют объёмной волне.'],['Confetti drift','Полёт конфетти','Rectangular paper pieces tumble as they fall.','Прямоугольные кусочки бумаги вращаются при падении.'],['Magnetic field','Магнитное поле','Short oriented strokes trace a changing force field.','Короткие направленные штрихи показывают изменяющееся силовое поле.']
 ],
 [
 ['Event horizon','Горизонт событий','A black disc sits inside a thin luminous ring.','Чёрный диск окружён тонким светящимся кольцом.'],['Nebula haze','Туманность','Diffuse coloured clouds overlap a dark starfield.','Рассеянные цветные облака перекрывают звёздное поле.'],['Distant sun','Далёкое солнце','A small star sends a broad glow across space.','Маленькая звезда посылает широкое свечение в космос.'],['Planet rise','Восход планеты','A giant shaded planet emerges below the frame.','Огромная затенённая планета появляется снизу.'],['Orbital rings','Орбитальные кольца','Thin concentric trajectories surround a small sun.','Тонкие концентрические траектории окружают маленькое солнце.'],['Lunar surface','Лунная поверхность','Offset shaded craters mark a monochrome surface.','Смещённые затенённые кратеры покрывают монохромную поверхность.'],['Galactic beam','Галактический луч','A narrow diagonal beam splits a cosmic cloud.','Узкий диагональный луч разделяет космическое облако.'],['Binary stars','Двойная звезда','Two distant points cast overlapping coronas.','Две далёкие точки отбрасывают пересекающиеся короны.'],['Ringed world','Мир с кольцом','An elliptical ring slices through a large sphere.','Эллиптическое кольцо пересекает большую сферу.'],['Redshift','Красное смещение','Spectral bands descend toward a dark horizon.','Спектральные полосы уходят к тёмному горизонту.'],
 ['Warp drive','Варп-прыжок','Radial star trails rush toward the viewer.','Радиальные звёздные следы летят навстречу зрителю.'],['Spiral galaxy','Спиральная галактика','Stars gather into three rotating spiral arms.','Звёзды собираются в три вращающихся спиральных рукава.'],['Solar system','Солнечная система','Planets orbit on independent elliptical tracks.','Планеты движутся по независимым эллиптическим орбитам.'],['Twilight planet','Сумеречная планета','A shaded world turns under a moving terminator.','Затенённый мир вращается под движущейся границей света.'],['Comet passage','Пролёт кометы','A bright nucleus pulls a curved trail behind it.','Яркое ядро тянет за собой изогнутый хвост.'],['Constellation map','Карта созвездий','Fixed stars and line segments rotate as a celestial map.','Звёзды и соединяющие их отрезки вращаются как небесная карта.'],['Accretion disc','Аккреционный диск','An inclined particle disc circles a dark centre.','Наклонный диск частиц вращается вокруг тёмного центра.'],['Pulsar','Пульсар','A compact star sweeps two opposing light beams.','Компактная звезда вращает два противоположных луча.'],['Asteroid belt','Пояс астероидов','Irregular rocks tumble on a broad orbital belt.','Неровные камни вращаются в широком орбитальном поясе.'],['Cosmic web','Космическая паутина','Luminous filaments connect distant bright nodes.','Светящиеся нити соединяют далёкие яркие узлы.']
 ],
 [
 ['Forest mist','Лесной туман','Dark triangular trees fade into pale fog.','Тёмные треугольные деревья растворяются в светлом тумане.'],['Ocean layers','Слои океана','Scalloped bands stack into quiet ocean waves.','Волнистые полосы складываются в спокойные морские волны.'],['Desert noon','Полдень в пустыне','A high sun hangs above a curved sand dune.','Высокое солнце висит над изогнутой песчаной дюной.'],['Leaf veins','Прожилки листа','Fine diagonal veins meet a central stem.','Тонкие диагональные прожилки встречаются у центрального стебля.'],['Wood rings','Годовые кольца','Irregularly spaced rings suggest a cut tree trunk.','Неравномерно расположенные кольца напоминают срез дерева.'],['Mountain dusk','Горные сумерки','Overlapping peaks divide a twilight sky.','Пересекающиеся вершины делят сумеречное небо.'],['Water caustics','Блики воды','Overlapping pale rings create a refracted light pattern.','Пересекающиеся светлые кольца создают узор преломлённого света.'],['Petal bed','Лепестки','Four radial lobes repeat as a flower tile.','Четыре радиальных лепестка повторяются цветочной плиткой.'],['Ice facets','Грани льда','Hard angled planes build a translucent frozen surface.','Чёткие наклонные плоскости образуют ледяную поверхность.'],['Moss stones','Камни во мху','Soft oval patches lie on a dark organic ground.','Мягкие овальные пятна лежат на тёмной природной основе.'],
 ['Rolling hills','Холмы','Layered silhouettes roll across a pastel landscape.','Слои силуэтов движутся по пастельному ландшафту.'],['Deep current','Глубинное течение','Many fine waves trace an underwater current.','Множество тонких волн показывают подводное течение.'],['Swaying grass','Колышущаяся трава','Curved blades bend together in a breeze.','Изогнутые травинки вместе склоняются на ветру.'],['Falling leaves','Листопад','Pointed leaves rotate as they float down.','Остроконечные листья вращаются в падении.'],['Rain window','Дождь на стекле','Long water streaks slide across a dim pane.','Длинные струйки воды стекают по тёмному стеклу.'],['Blooming garden','Цветущий сад','Radial petal clusters open at staggered intervals.','Радиальные группы лепестков раскрываются по очереди.'],['Lightning sky','Грозовое небо','A slowly travelling forked bolt glows over clouds.','Медленно движущаяся разветвлённая молния светится над облаками.'],['Coral branches','Ветви коралла','Recursive branches sway in an underwater palette.','Рекурсивные ветви колышутся в подводной палитре.'],['Cloud drift','Плывущие облака','Soft cloud clusters move at different depths.','Мягкие группы облаков движутся на разной глубине.'],['Ripple pond','Круги на воде','Expanding circles emerge from several water drops.','Расширяющиеся круги расходятся от нескольких капель.']
 ],
 [
 ['Memphis cutouts','Мемфис','Graphic circles and diagonal scraps form a collage.','Графические круги и диагональные фрагменты образуют коллаж.'],['Liquid chrome','Жидкий хром','High-contrast radial bands resemble polished metal.','Контрастные радиальные полосы напоминают полированный металл.'],['Paper collage','Бумажный коллаж','Angled paper planes overlap in a bold composition.','Наклонные бумажные плоскости пересекаются в яркой композиции.'],['Op art','Оп-арт','Dense concentric stripes create an optical vibration.','Плотные концентрические полосы создают оптическую вибрацию.'],['Split personality','Двойственность','Two halves meet along a hard diagonal cut.','Две половины встречаются на чётком диагональном срезе.'],['Ink cloud','Чернильное облако','Soft dark pools spread on a warm paper base.','Мягкие тёмные пятна растекаются по тёплой бумаге.'],['Ribbon stack','Стопка лент','Alternating diagonal bands build a folded ribbon.','Чередующиеся диагональные полосы складываются в ленту.'],['Colour lens','Цветная линза','Translucent circular lenses overlap a split field.','Полупрозрачные круглые линзы перекрывают разделённое поле.'],['Zigzag pulse','Зигзаг','Sharp chevrons form a repeated optical pulse.','Острые шевроны создают повторяющийся оптический пульс.'],['Folded fan','Складной веер','Many conic bands converge into a folded fan.','Множество конических полос сходится в складной веер.'],
 ['Flow lines','Линии потока','Continuous strands follow a sinusoidal flow field.','Непрерывные нити следуют синусоидальному полю.'],['Metaball dance','Танец сфер','Large translucent orbs move through overlapping paths.','Большие полупрозрачные сферы движутся по пересекающимся траекториям.'],['Lissajous','Лиссажу','Two oscillations draw a closed harmonic loop.','Два колебания рисуют замкнутую гармоническую петлю.'],['Ink ribbons','Чернильные ленты','Wide translucent strokes coil into a loose knot.','Широкие полупрозрачные штрихи свиваются в свободный узел.'],['Fluid cells','Жидкие ячейки','A field of organic loops stretches and contracts.','Поле органических петель растягивается и сжимается.'],['Kaleidoscope','Калейдоскоп','Mirrored triangles orbit in radial symmetry.','Зеркальные треугольники вращаются в радиальной симметрии.'],['Sound sculpture','Звуковая скульптура','Synthetic waveforms draw a layered audio-like sculpture.','Синтетические волны рисуют многослойную звуковую скульптуру.'],['Scribble study','Этюд каракулей','Deterministic looping strokes form an expressive tangle.','Зацикленные штрихи образуют выразительный клубок.'],['Ribbon sphere','Сфера из лент','Projected latitude lines rotate around an invisible sphere.','Проекции параллелей вращаются вокруг невидимой сферы.'],['Moire motion','Движение муара','Two fine line grids shift across one another.','Две тонкие линейные сетки смещаются друг относительно друга.']
 ],
 [
 ['Neon grid','Неоновая сетка','Bright orthogonal lines glow on an ink field.','Яркие ортогональные линии светятся на чернильном поле.'],['Vaporwave sun','Солнце синтвейва','A striped sunset floats above a purple horizon.','Полосатый закат парит над фиолетовым горизонтом.'],['Arcade carpet','Ковёр аркады','Bright diagonal dashes repeat on a dark floor.','Яркие диагональные штрихи повторяются на тёмном поле.'],['CRT scanlines','Строки кинескопа','Horizontal scanlines interrupt a soft screen glow.','Горизонтальные строки прерывают мягкое свечение экрана.'],['Laser cross','Лазерный крест','Two sharp luminous beams intersect at the centre.','Два резких светящихся луча пересекаются в центре.'],['Disco tiles','Плитка диско','Alternating saturated squares evoke a dance floor.','Чередующиеся насыщенные квадраты напоминают танцпол.'],['Retro rays','Ретро-лучи','A warm sunburst radiates from the lower edge.','Тёплые солнечные лучи расходятся от нижнего края.'],['Cassette stripes','Кассетные полосы','Broad vintage bands cross a warm neutral surface.','Широкие винтажные полосы пересекают тёплую нейтральную поверхность.'],['Pixel sunset','Пиксельный закат','Stepped horizontal bands make a low-resolution horizon.','Ступенчатые горизонтальные полосы образуют пиксельный горизонт.'],['Neon frame','Неоновая рамка','Inset glowing borders create a luminous doorway.','Вложенные светящиеся границы создают световой проход.'],
 ['Outrun highway','Шоссе синтвейва','Perspective road lines rush toward a striped sun.','Линии дороги в перспективе движутся к полосатому солнцу.'],['Digital rain','Цифровой дождь','Columns of original glyphs cascade down a dark screen.','Столбцы символов каскадом падают по тёмному экрану.'],['Equalizer','Эквалайзер','Independent bars follow a synthetic audio rhythm.','Отдельные полосы следуют синтетическому звуковому ритму.'],['Laser tunnel','Лазерный тоннель','Luminous polygon frames expand toward the viewer.','Светящиеся многоугольные рамки расширяются навстречу зрителю.'],['Pixel invaders','Пиксельные гости','Small mirrored pixel creatures bob in formation.','Маленькие зеркальные пиксельные существа движутся строем.'],['Neon city','Неоновый город','Layered city towers display blinking window grids.','Слои городских башен показывают мигающие сетки окон.'],['Radar sweep','Луч радара','A rotating wedge reveals targets on a circular scope.','Вращающийся сектор раскрывает цели на круглом радаре.'],['Synth strings','Струны синтезатора','Glowing waveform strings ripple around a centre line.','Светящиеся волновые струны колышутся вокруг центральной линии.'],['Disco orbit','Орбита диско','A faceted sphere reflects shifting light tiles.','Гранёная сфера отражает движущиеся световые плитки.'],['Glitch strips','Полосы помех','Horizontal fragments drift with occasional lateral offsets.','Горизонтальные фрагменты дрейфуют с боковыми смещениями.']
 ],
 [
 ['Warm paper','Тёплая бумага','Fine fibres cross a warm off-white sheet.','Тонкие волокна пересекают тёплый светлый лист.'],['Linen weave','Льняное плетение','Crossed translucent threads build a linen texture.','Пересечённые полупрозрачные нити образуют текстуру льна.'],['Quiet dots','Тихие точки','Tiny muted points sit on a spacious pale grid.','Маленькие приглушённые точки лежат на просторной светлой сетке.'],['Soft corner','Мягкий угол','One gentle radial shadow anchors an empty field.','Одна мягкая радиальная тень закрепляет пустое поле.'],['Fine pinstripe','Тонкая полоска','Restrained vertical lines add a measured rhythm.','Сдержанные вертикальные линии задают размеренный ритм.'],['Brushed metal','Шлифованный металл','Fine horizontal streaks cross a silver highlight.','Тонкие горизонтальные штрихи пересекают серебристый блик.'],['Checker whisper','Тихая клетка','Low-contrast checker tiles form a subtle surface.','Неконтрастная шахматная плитка создаёт деликатную поверхность.'],['Arch study','Этюд арки','An offset ring frames a calm neutral field.','Смещённое кольцо обрамляет спокойное нейтральное поле.'],['Blueprint light','Светлый чертёж','Thin grid lines meet on a pale technical page.','Тонкие линии сетки встречаются на светлом техническом листе.'],['Carbon fibre','Углеволокно','Small angled facets create a dark woven finish.','Маленькие наклонные грани создают тёмное плетёное покрытие.'],
 ['Contour lines','Контурные линии','Slow nested contours shift like a topographic map.','Медленные вложенные контуры смещаются как топографическая карта.'],['Quiet orbit','Тихая орбита','A single point travels around an understated ellipse.','Одна точка движется по сдержанному эллипсу.'],['Drifting grain','Движущееся зерно','Sparse tiny flecks translate over a matte field.','Редкие маленькие вкрапления движутся по матовой поверхности.'],['Line horizon','Линейный горизонт','Three nearly flat waves cross a spacious canvas.','Три почти плоские волны пересекают просторный холст.'],['Breathing circle','Дыхание круга','One thin circular outline expands and contracts.','Один тонкий круг расширяется и сжимается.'],['Soft rain','Мягкий дождь','Short vertical marks fall in a restrained pattern.','Короткие вертикальные штрихи падают в сдержанном узоре.'],['Woven motion','Движущееся полотно','Fine interlaced curves slide past each other.','Тонкие переплетённые кривые скользят друг относительно друга.'],['Balance','Равновесие','Two floating discs counterbalance a fine centre line.','Два парящих диска уравновешивают тонкую центральную линию.'],['Dotted wave','Точечная волна','A single row of points follows a subtle travelling wave.','Один ряд точек следует мягкой бегущей волне.'],['Paper shadows','Бумажные тени','Offset translucent panels cast moving geometric shadows.','Смещённые полупрозрачные панели отбрасывают подвижные геометрические тени.']
 ]
];
const PALETTES = [
 ['#c9fa70','#b1e9ff','#163338'],['#b3a0ff','#f2a5d6','#242043'],['#71ddff','#fcdb91','#0c2434'],['#aa89ff','#ffba92','#080b21'],['#80d7b1','#f2d1a1','#163f42'],['#ff87b4','#acb7ff','#29203d'],['#ff55cd','#60e1ff','#160e36'],['#9c9589','#c5bda9','#eeeae0']
];
const BACKGROUNDS = CATEGORIES.flatMap((cat,g)=>NAMES[g].map((n,i)=>{
 const light=(g===7&&i!==9)||(g===0&&[1,6].includes(i))||(g===1&&[1,6,7].includes(i))||(g===4&&[2,7,8].includes(i))||(g===5&&[2,5,7].includes(i))||(g===6&&i===7);
 const colors=[...PALETTES[g]]; if(light&&g!==7)colors[2]='#f0e5d7';
 if(g===7&&i===9){colors[0]='#747a81';colors[1]='#353940';colors[2]='#17191d'}
 if(g===0&&i===1){colors[0]='#b7a0f1';colors[1]='#ffa4cf';colors[2]='#c0dbfc'}
 if(g===0&&i===2){colors[0]='#ff733d';colors[1]='#c449d3'}
 return {id:cat.id+'-'+String(i+1).padStart(2,'0'),category:cat.id,g,i,name:{en:n[0],ru:n[1]},description:{en:n[2],ru:n[3]},tech:i<10?'CSS':'Canvas',animated:i>=10||(g===0&&[0,1,2,3,4,6,9].includes(i)),tone:light?'light':'dark',colors,number:g*20+i+1};
}));
if(typeof module!=='undefined')module.exports={CATEGORIES,BACKGROUNDS,NAMES};
